// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: beacon/v1/beacon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Weight        int32                  `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Health        string                 `protobuf:"bytes,9,opt,name=health,proto3" json:"health,omitempty"`
	Region        string                 `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string                 `protobuf:"bytes,11,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_beacon_v1_beacon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_v1_beacon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_beacon_v1_beacon_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instance) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Instance) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Instance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Instance) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Instance) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Instance) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Instance) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Instance) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *Instance) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Instance) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_beacon_v1_beacon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_v1_beacon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_beacon_v1_beacon_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_beacon_v1_beacon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_v1_beacon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_beacon_v1_beacon_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_beacon_v1_beacon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_v1_beacon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_beacon_v1_beacon_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Passing       bool                   `protobuf:"varint,2,opt,name=passing,proto3" json:"passing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_beacon_v1_beacon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_v1_beacon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_beacon_v1_beacon_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ResolveRequest) GetPassing() bool {
	if x != nil {
		return x.Passing
	}
	return false
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*Instance            `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_beacon_v1_beacon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_v1_beacon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_beacon_v1_beacon_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveResponse) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ResolveResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	FromIndex     uint64                 `protobuf:"varint,2,opt,name=from_index,json=fromIndex,proto3" json:"from_index,omitempty"`
	Passing       bool                   `protobuf:"varint,3,opt,name=passing,proto3" json:"passing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_beacon_v1_beacon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_v1_beacon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_beacon_v1_beacon_proto_rawDescGZIP(), []int{6}
}

func (x *WatchRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WatchRequest) GetFromIndex() uint64 {
	if x != nil {
		return x.FromIndex
	}
	return 0
}

func (x *WatchRequest) GetPassing() bool {
	if x != nil {
		return x.Passing
	}
	return false
}

type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // SNAPSHOT | ADD | UPDATE | REMOVE
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Instances     []*Instance            `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty"`
	Index         uint64                 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_beacon_v1_beacon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_v1_beacon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_beacon_v1_beacon_proto_rawDescGZIP(), []int{7}
}

func (x *WatchEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WatchEvent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WatchEvent) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *WatchEvent) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type WatchMultiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"` // subscribe | unsubscribe
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	FromIndex     uint64                 `protobuf:"varint,3,opt,name=from_index,json=fromIndex,proto3" json:"from_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchMultiRequest) Reset() {
	*x = WatchMultiRequest{}
	mi := &file_beacon_v1_beacon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchMultiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMultiRequest) ProtoMessage() {}

func (x *WatchMultiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_v1_beacon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMultiRequest.ProtoReflect.Descriptor instead.
func (*WatchMultiRequest) Descriptor() ([]byte, []int) {
	return file_beacon_v1_beacon_proto_rawDescGZIP(), []int{8}
}

func (x *WatchMultiRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *WatchMultiRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WatchMultiRequest) GetFromIndex() uint64 {
	if x != nil {
		return x.FromIndex
	}
	return 0
}

// CatalogDelta is piggybacked on SWIM gossip.
type CatalogDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // register | deregister | health
	Instance      *Instance              `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Health        string                 `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	Index         uint64                 `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Origin        string                 `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	Incarnation   uint64                 `protobuf:"varint,7,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	TraceId       string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogDelta) Reset() {
	*x = CatalogDelta{}
	mi := &file_beacon_v1_beacon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogDelta) ProtoMessage() {}

func (x *CatalogDelta) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_v1_beacon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogDelta.ProtoReflect.Descriptor instead.
func (*CatalogDelta) Descriptor() ([]byte, []int) {
	return file_beacon_v1_beacon_proto_rawDescGZIP(), []int{9}
}

func (x *CatalogDelta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CatalogDelta) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *CatalogDelta) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CatalogDelta) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *CatalogDelta) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CatalogDelta) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CatalogDelta) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *CatalogDelta) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_beacon_v1_beacon_proto protoreflect.FileDescriptor

const file_beacon_v1_beacon_proto_rawDesc = "" +
	"\n" +
	"\x16beacon/v1/beacon.proto\x12\tbeacon.v1\"\xd2\x02\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x121\n" +
	"\x04meta\x18\a \x03(\v2\x1d.beacon.v1.Instance.MetaEntryR\x04meta\x12\x16\n" +
	"\x06weight\x18\b \x01(\x05R\x06weight\x12\x16\n" +
	"\x06health\x18\t \x01(\tR\x06health\x12\x16\n" +
	"\x06region\x18\n" +
	" \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\v \x01(\tR\x04zone\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x0fRegisterRequest\x12/\n" +
	"\binstance\x18\x01 \x01(\v2\x13.beacon.v1.InstanceR\binstance\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\"#\n" +
	"\x11DeregisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x0eResolveRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\apassing\x18\x02 \x01(\bR\apassing\"Z\n" +
	"\x0fResolveResponse\x121\n" +
	"\tinstances\x18\x01 \x03(\v2\x13.beacon.v1.InstanceR\tinstances\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"a\n" +
	"\fWatchRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"from_index\x18\x02 \x01(\x04R\tfromIndex\x12\x18\n" +
	"\apassing\x18\x03 \x01(\bR\apassing\"\x83\x01\n" +
	"\n" +
	"WatchEvent\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x121\n" +
	"\tinstances\x18\x03 \x03(\v2\x13.beacon.v1.InstanceR\tinstances\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x04R\x05index\"\\\n" +
	"\x11WatchMultiRequest\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"from_index\x18\x03 \x01(\x04R\tfromIndex\"\xf7\x01\n" +
	"\fCatalogDelta\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12/\n" +
	"\binstance\x18\x02 \x01(\v2\x13.beacon.v1.InstanceR\binstance\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06health\x18\x04 \x01(\tR\x06health\x12\x14\n" +
	"\x05index\x18\x05 \x01(\x04R\x05index\x12\x16\n" +
	"\x06origin\x18\x06 \x01(\tR\x06origin\x12 \n" +
	"\vincarnation\x18\a \x01(\x04R\vincarnation\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId2\xdd\x02\n" +
	"\tDiscovery\x12C\n" +
	"\bRegister\x12\x1a.beacon.v1.RegisterRequest\x1a\x1b.beacon.v1.RegisterResponse\x12G\n" +
	"\n" +
	"Deregister\x12\x1c.beacon.v1.DeregisterRequest\x1a\x1b.beacon.v1.RegisterResponse\x12@\n" +
	"\aResolve\x12\x19.beacon.v1.ResolveRequest\x1a\x1a.beacon.v1.ResolveResponse\x129\n" +
	"\x05Watch\x12\x17.beacon.v1.WatchRequest\x1a\x15.beacon.v1.WatchEvent0\x01\x12E\n" +
	"\n" +
	"WatchMulti\x12\x1c.beacon.v1.WatchMultiRequest\x1a\x15.beacon.v1.WatchEvent(\x010\x01B)Z'github.com/sanskar/beacon/pkg/api/pb;pbb\x06proto3"

var (
	file_beacon_v1_beacon_proto_rawDescOnce sync.Once
	file_beacon_v1_beacon_proto_rawDescData []byte
)

func file_beacon_v1_beacon_proto_rawDescGZIP() []byte {
	file_beacon_v1_beacon_proto_rawDescOnce.Do(func() {
		file_beacon_v1_beacon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beacon_v1_beacon_proto_rawDesc), len(file_beacon_v1_beacon_proto_rawDesc)))
	})
	return file_beacon_v1_beacon_proto_rawDescData
}

var file_beacon_v1_beacon_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_beacon_v1_beacon_proto_goTypes = []any{
	(*Instance)(nil),          // 0: beacon.v1.Instance
	(*RegisterRequest)(nil),   // 1: beacon.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 2: beacon.v1.RegisterResponse
	(*DeregisterRequest)(nil), // 3: beacon.v1.DeregisterRequest
	(*ResolveRequest)(nil),    // 4: beacon.v1.ResolveRequest
	(*ResolveResponse)(nil),   // 5: beacon.v1.ResolveResponse
	(*WatchRequest)(nil),      // 6: beacon.v1.WatchRequest
	(*WatchEvent)(nil),        // 7: beacon.v1.WatchEvent
	(*WatchMultiRequest)(nil), // 8: beacon.v1.WatchMultiRequest
	(*CatalogDelta)(nil),      // 9: beacon.v1.CatalogDelta
	nil,                       // 10: beacon.v1.Instance.MetaEntry
}
var file_beacon_v1_beacon_proto_depIdxs = []int32{
	10, // 0: beacon.v1.Instance.meta:type_name -> beacon.v1.Instance.MetaEntry
	0,  // 1: beacon.v1.RegisterRequest.instance:type_name -> beacon.v1.Instance
	0,  // 2: beacon.v1.ResolveResponse.instances:type_name -> beacon.v1.Instance
	0,  // 3: beacon.v1.WatchEvent.instances:type_name -> beacon.v1.Instance
	0,  // 4: beacon.v1.CatalogDelta.instance:type_name -> beacon.v1.Instance
	1,  // 5: beacon.v1.Discovery.Register:input_type -> beacon.v1.RegisterRequest
	3,  // 6: beacon.v1.Discovery.Deregister:input_type -> beacon.v1.DeregisterRequest
	4,  // 7: beacon.v1.Discovery.Resolve:input_type -> beacon.v1.ResolveRequest
	6,  // 8: beacon.v1.Discovery.Watch:input_type -> beacon.v1.WatchRequest
	8,  // 9: beacon.v1.Discovery.WatchMulti:input_type -> beacon.v1.WatchMultiRequest
	2,  // 10: beacon.v1.Discovery.Register:output_type -> beacon.v1.RegisterResponse
	2,  // 11: beacon.v1.Discovery.Deregister:output_type -> beacon.v1.RegisterResponse
	5,  // 12: beacon.v1.Discovery.Resolve:output_type -> beacon.v1.ResolveResponse
	7,  // 13: beacon.v1.Discovery.Watch:output_type -> beacon.v1.WatchEvent
	7,  // 14: beacon.v1.Discovery.WatchMulti:output_type -> beacon.v1.WatchEvent
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_beacon_v1_beacon_proto_init() }
func file_beacon_v1_beacon_proto_init() {
	if File_beacon_v1_beacon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beacon_v1_beacon_proto_rawDesc), len(file_beacon_v1_beacon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beacon_v1_beacon_proto_goTypes,
		DependencyIndexes: file_beacon_v1_beacon_proto_depIdxs,
		MessageInfos:      file_beacon_v1_beacon_proto_msgTypes,
	}.Build()
	File_beacon_v1_beacon_proto = out.File
	file_beacon_v1_beacon_proto_goTypes = nil
	file_beacon_v1_beacon_proto_depIdxs = nil
}
