# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beacon < Formula
  desc "Consul-class service discovery — gossip + Raft catalog, DNS/HTTP/gRPC/xDS"
  homepage "https://github.com/sanskarpan/beacon"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.1.0/beacon_0.1.0_darwin_amd64.tar.gz"
      sha256 "2813b0cf7cf45c1bb2827cd33616073abf37e6ee5c24985feb410283b36ed886"

      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.1.0/beacon_0.1.0_darwin_arm64.tar.gz"
      sha256 "42f511a6298d049f2d436d578d4074d6e9337c756a9d0ab2eeedcddf0083184d"

      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.1.0/beacon_0.1.0_linux_amd64.tar.gz"
      sha256 "c053ae0f413d9938ec594f1af5b90ccf74380e231f4b8ea171ce138e7b88607c"
      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.1.0/beacon_0.1.0_linux_arm64.tar.gz"
      sha256 "43b70f4061e707f6ef52dced93fd0c4c29fa7cd6ebb5f2df02fcd0c7c750ed69"
      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
  end
end
