# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beacon < Formula
  desc "Consul-class service discovery — gossip + Raft catalog, DNS/HTTP/gRPC/xDS"
  homepage "https://github.com/sanskarpan/beacon"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.2.0/beacon_0.2.0_darwin_amd64.tar.gz"
      sha256 "fc2b447ee4f691fd51fb8940924f6d616bbd9661e3f608be7395d3c1eda62381"

      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.2.0/beacon_0.2.0_darwin_arm64.tar.gz"
      sha256 "f8e1d8d5a63ee590c0a342d80c60d6f07a92e28d2b98344c9c5dbd4733e1b6df"

      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.2.0/beacon_0.2.0_linux_amd64.tar.gz"
      sha256 "6e71003d9149b2e7dc2447d2ac4a54562ff2726446cd201b562e9cdee90402d2"
      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.2.0/beacon_0.2.0_linux_arm64.tar.gz"
      sha256 "0a6078f69b34bee610de26ca7caacf5597fd3410d3f32f86309ad517d967146f"
      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
  end
end
