# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beacon < Formula
  desc "Consul-class service discovery — gossip + Raft catalog, DNS/HTTP/gRPC/xDS"
  homepage "https://github.com/sanskarpan/beacon"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.1.0/beacon_0.1.0_darwin_amd64.tar.gz"
      sha256 "25209a3dbbd0e098e057d8d7b2f2ac2e04dd3205ecef3968f40726bf835a2fa3"

      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.1.0/beacon_0.1.0_darwin_arm64.tar.gz"
      sha256 "59f0032e4039e1ec74aeccd85287ede4635a9dcd2d7ec71cee2a04baa9e76f19"

      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.1.0/beacon_0.1.0_linux_amd64.tar.gz"
      sha256 "bff267156c329571fd831a1aacf90833f780abc77b1286ad8245110b6b1f4ca8"
      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanskarpan/beacon/releases/download/v0.1.0/beacon_0.1.0_linux_arm64.tar.gz"
      sha256 "4c7651f29f2917a579c23950054b74cf3d68a23853c810f8eab2398580195bf4"
      define_method(:install) do
        bin.install "beacon"
        bin.install "beacon-agent"
        bin.install "beacon-server"
      end
    end
  end
end
